GAMETITLE = 'Slide Puzzle'
BOARDWIDTH = 4      # number of columns in board
BOARDHEIGHT = 4     # number of rows in board 
TILESIZE = 80       # pixel size of each tile piece
WINDOWWIDTH = 640
WINDOWHEIGHT = 480
RESOLUTION = WINDOWWIDTH , WINDOWHEIGHT
FPS = 30 
BLANK = None

BLACK = 0,0,0
WHITE = 255,255,255
BRIGHTBLUE = 0,50,255
DARKTURQUOISE = 3,54,73
GREEN = 0,204,0

BGCOLOR = DARKTURQUOISE
TILECOLOR = GREEN
TEXTCOLOR = WHITE
BORDERCOLOR = BRIGHTBLUE 
FONTSIZE = 20 
FONTSTYLE = r'..\font\freesansbold.ttf'
BUTTONCOLOR = WHITE 
BUTTONTEXTCOLOR = BLACK 
MESSAGECOLOR = WHITE 
RESTARTPOSITION = WINDOWWIDTH - 150 , WINDOWHEIGHT - ((TILESIZE//2) * 3)
QUITPOSITION = WINDOWWIDTH - 150 , WINDOWHEIGHT - ((TILESIZE//2) * 2)
ACTIONPOSITION = 20,30

XMARGIN = int((WINDOWWIDTH-(TILESIZE*BOARDWIDTH+(BOARDWIDTH-1)))/2)
YMARGIN = int((WINDOWHEIGHT-(TILESIZE*BOARDHEIGHT+(BOARDHEIGHT-1)))/2)

UP = 'up'
DOWN = 'down'
LEFT = 'left'
RIGHT = 'right'
