WINDOWWIDTH = 640
WINDOWHEIGHT = 480
RESOLUTION = WINDOWWIDTH,WINDOWHEIGHT
BOARDWIDTH = 10     #number of horizontal boxes 
BOARDHEIGHT = 20    #number of vertical boxes
BOXSIZE = 20
X_OFFSET =  int((WINDOWWIDTH - (BOARDWIDTH*BOXSIZE)) / 2)
Y_OFFSET =  65


FPS = 25 
BLANK = '.'

TEMPLATEWIDTH = 5 
TEMPLATEHEIGHT = 5 

S_SHAPE_TEMPLATE = []